use super::dialect::{check_ident, qualify, safe_cast_type, Ctx, Dialect, Quote, Sql};

pub struct PgDialect;

fn qualified(ctx: &Ctx) -> String {
    let table = check_ident(&ctx.table, "表名").unwrap_or_else(|_| ctx.table.clone());
    if ctx.schema.is_empty() {
        qualify(Quote::Double, &[&table])
    } else {
        let schema = check_ident(&ctx.schema, "模式名").unwrap_or_else(|_| ctx.schema.clone());
        qualify(Quote::Double, &[&schema, &table])
    }
}

impl Dialect for PgDialect {
    fn name(&self) -> &'static str {
        "postgres"
    }
    fn quote(&self) -> Quote {
        Quote::Double
    }
    fn has_schemas(&self) -> bool {
        true
    }
    fn paging(&self, limit: u64, offset: u64) -> String {
        format!("LIMIT {limit} OFFSET {offset}")
    }
    fn table_name(&self, ctx: &Ctx) -> String {
        qualified(ctx)
    }
    fn cast_text(&self, col: &str) -> String {
        format!("{col}::text")
    }
    fn compare(&self, col: &str, ty: &str) -> String {
        format!("{col} = CAST(? AS {})", safe_cast_type(ty))
    }
    fn assign(&self, col: &str, ty: &str) -> String {
        format!("{col} = CAST(? AS {})", safe_cast_type(ty))
    }
    fn value_placeholder(&self, ty: &str) -> String {
        format!("CAST(? AS {})", safe_cast_type(ty))
    }
    fn id_type(&self) -> &'static str {
        "BIGINT"
    }
    fn auto_increment(&self) -> &'static str {
        "GENERATED BY DEFAULT AS IDENTITY"
    }
    fn version_sql(&self) -> Sql {
        Sql::new("SELECT version() AS version")
    }
    fn current_db_sql(&self) -> Option<Sql> {
        Some(Sql::new("SELECT current_database() AS name"))
    }
    fn count_sql(&self, ctx: &Ctx) -> Sql {
        Sql::new(format!("SELECT COUNT(*) AS row_count FROM {}", qualified(ctx)))
    }
    fn databases_sql(&self, _ctx: &Ctx) -> Sql {
        Sql::new("SELECT datname AS name FROM pg_database WHERE datallowconn ORDER BY name")
    }
    fn schemas_sql(&self, _ctx: &Ctx) -> Sql {
        Sql::new(
            "SELECT nspname AS name FROM pg_namespace \
             WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema' ORDER BY name",
        )
    }
    fn tables_sql(&self, ctx: &Ctx) -> Sql {
        Sql::with(
            "SELECT c.relname AS name, CASE WHEN c.relkind IN ('v','m') THEN 'view' ELSE 'table' END AS kind, \
             CASE WHEN c.reltuples::bigint < 0 THEN NULL ELSE c.reltuples::bigint END AS row_estimate, \
             pg_total_relation_size(c.oid) AS size_bytes, obj_description(c.oid) AS comment \
             FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace \
             WHERE n.nspname = ? AND c.relkind IN ('r','p','v','m','f') ORDER BY c.relname".to_string(),
            vec![ctx.schema.clone()],
        )
    }
    fn columns_sql(&self, ctx: &Ctx) -> Sql {
        Sql::with(
            "SELECT a.attnum AS ord, a.attname AS name, format_type(a.atttypid, a.atttypmod) AS type, \
             NULL AS size, CASE WHEN a.attnotnull THEN 0 ELSE 1 END AS nullable, \
             pg_get_expr(d.adbin, d.adrelid) AS default_value, \
             COALESCE(col_description(a.attrelid, a.attnum), '') AS comment, \
             CASE WHEN a.attidentity <> '' THEN 'identity' \
                  WHEN a.attgenerated = 's' THEN 'generated' \
                  WHEN pg_get_serial_sequence(n.nspname || '.' || c.relname, a.attname) IS NOT NULL THEN 'serial' \
                  ELSE '' END AS extra \
             FROM pg_attribute a \
             JOIN pg_class c ON c.oid = a.attrelid \
             JOIN pg_namespace n ON n.oid = c.relnamespace \
             LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum \
             WHERE n.nspname = ? AND c.relname = ? AND a.attnum > 0 AND NOT a.attisdropped \
             ORDER BY a.attnum"
                .to_string(),
            vec![ctx.schema.clone(), ctx.table.clone()],
        )
    }
    fn pk_sql(&self, ctx: &Ctx) -> Sql {
        Sql::with(
            "SELECT string_agg(a.attname::text, ', ' ORDER BY array_position(k.conkey, a.attnum)) AS pk_columns \
             FROM pg_constraint k \
             JOIN pg_class c ON c.oid = k.conrelid \
             JOIN pg_namespace n ON n.oid = c.relnamespace \
             JOIN pg_attribute a ON a.attrelid = k.conrelid AND a.attnum = ANY(k.conkey) \
             WHERE k.contype = 'p' AND n.nspname = ? AND c.relname = ?"
                .to_string(),
            vec![ctx.schema.clone(), ctx.table.clone()],
        )
    }
    fn fk_sql(&self, ctx: &Ctx) -> Sql {
        Sql::with(
            "SELECT k.conname AS fk_name, a.attname AS column_name, rt.relname AS ref_table, \
             ra.attname AS ref_column, \
             CASE k.confdeltype WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' \
                  WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END AS on_delete, \
             CASE k.confupdtype WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' \
                  WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END AS on_update \
             FROM pg_constraint k \
             JOIN pg_class c ON c.oid = k.conrelid \
             JOIN pg_namespace n ON n.oid = c.relnamespace \
             JOIN pg_class rt ON rt.oid = k.confrelid \
             CROSS JOIN LATERAL unnest(k.conkey, k.confkey) WITH ORDINALITY AS x(attnum, rattnum, ord) \
             JOIN pg_attribute a ON a.attrelid = k.conrelid AND a.attnum = x.attnum \
             JOIN pg_attribute ra ON ra.attrelid = k.confrelid AND ra.attnum = x.rattnum \
             WHERE k.contype = 'f' AND n.nspname = ? AND c.relname = ? \
             ORDER BY k.conname, x.ord"
                .to_string(),
            vec![ctx.schema.clone(), ctx.table.clone()],
        )
    }
    fn index_sql(&self, ctx: &Ctx) -> Sql {
        Sql::with(
            "SELECT i.relname AS index_name, CASE WHEN ix.indisunique THEN 1 ELSE 0 END AS is_unique, \
             CASE WHEN ix.indisprimary THEN 1 ELSE 0 END AS is_primary, am.amname AS index_kind, \
             (SELECT string_agg(a.attname::text, ', ' ORDER BY x.ord) \
                FROM unnest(ix.indkey) WITH ORDINALITY x(attnum, ord) \
                JOIN pg_attribute a ON a.attrelid = ix.indrelid AND a.attnum = x.attnum) AS column_list \
             FROM pg_index ix \
             JOIN pg_class i ON i.oid = ix.indexrelid \
             JOIN pg_class c ON c.oid = ix.indrelid \
             JOIN pg_namespace n ON n.oid = c.relnamespace \
             JOIN pg_am am ON am.oid = i.relam \
             WHERE n.nspname = ? AND c.relname = ? ORDER BY is_primary DESC, i.relname"
                .to_string(),
            vec![ctx.schema.clone(), ctx.table.clone()],
        )
    }
    fn ddl_sql(&self, _ctx: &Ctx) -> Option<Sql> {
        None
    }
    fn set_schema_sql(&self, schema: &str) -> Option<String> {
        let s = check_ident(schema, "模式名").ok()?;
        Some(format!("SET search_path TO {}, public", qualify(Quote::Double, &[&s])))
    }
}
